### PR TITLE
Make the Repo Great Again

### PR DESCRIPTION
**Pull request by NicholasKobald**
- deletes duel.py file that I don't think we'll ever want to use
- deletes unused variables all over the place
- lets pycharm lint the code a little

### CODE REVIEW

**Comment by NicholasKobald** [comment]
we could probably also delete a lot of Voronoi logic, I'm pretty sure we shouldn't end up using that

**Comment by NicholasKobald** [comment]
> again

I like the attitude

**Comment by jcgallegdup** [comment]
I'm thinking of going through the code to remember how it works, fix & refactor stuff (now that we both have more Python dev experience), add `TODO`s, and document functions.

**Comment by NicholasKobald** [comment]
Was there any reason not to use python 3? probably not painful to update

**Comment by NicholasKobald** [comment]
image
 i know git

**Comment by NicholasKobald** [comment]
So I think I stripped away a lot of the garbagey stuff. Right now it's just using the food fetcher logic which I think we're reasonably confident does work. Mostly. 

Playing around our snake did weird things once or twice. Idk you mentioned some weirdness in in food fetching but I think it was probably latency between docker and the snake..

It looks like we might be falling out of date with what the new api is, which is over here: https://github.com/battle-snake/battle_snake

**Comment by NicholasKobald** [comment]
@jcgallegdup @jcgallegdup @jcgallegdup @jcgallegdup

**Pull request merged**
